swagger: "2.0"
info:
  description: Swagger file
  version: "1.0.0"
  title: Swagger REST todo-list
consumes:
  - application/json
produces:
  - application/json

basePath: /

paths:
  /todo:
    get:
      operationId: todolist.readAll
      tags:
        - Todo-list
      summary: Read all todo list
      description: Read all todo list
      responses:
        200:
          description: Success to read all list
          schema:
            type: array
            items:
              properties:
                key:
                  type: string
                  description: Task key
                task:
                  type: string
                  description: The task
                details:
                  type: string
                  description: Task details
                status:
                  type: string
                  description: Task status (pending or completed)
                timestampCreate:
                  type: string
                  description: Task creation timestamp
    post:
      operationId: todolist.create
      tags:
        - Todo-list
      summary: Create a new task in the todo list
      description: Create a new task in the todo list
      parameters:
        - name: data
          in: body
          description: Task to be created
          required: True
          schema:
            type: object
            required:
              - key
              - task
              - status
            properties:
              key:
                type: string
                description: Task tey, can't have space
              task:
                type: string
                description: The task
              details:
                type: string
                description: Task details
              status:
                type: string
                description: Task status (pending or completed)
                default: pending
      responses:
        201:
          description: Success

  /todo/{key}:
    get:
      operationId: todolist.readOne
      tags:
        - Todo-list
      summary: Read a task from todo list
      description: Read a task from todo list
      parameters:
        - name: key
          in: path
          description: Task key
          type: string
          required: True
      responses:
        200:
          description: Success
          schema:
            properties:
              key:
                type: string
                description: Task key
              task:
                type: string
                description: The task
              details:
                type: string
                description: Task details
              status:
                type: string
                description: Task status (pending or completed)
              timestampCreate:
                type: string
                description: Task creation timestamp

    put:
      operationId: todolist.update
      tags:
        - Todo-list
      summary: Update a task from todo list
      description: Update a task from todo list
      parameters:
        - name: key
          in: path
          type: string
          description: Task key
          required: True
        - name: data
          in: body
          schema:
            type: object
            required:
              - task
              - status
            properties:
              task:
                type: string
                description: The task
              details:
                type: string
                description: Task details
              status:
                type: string
                description: Task status (pending or completed)
      responses:
        200:
          description: Success

    delete:
      operationId: todolist.delete
      tags:
        - Todo-list
      summary: Delete a task from todo list
      description: Delete a task from todo list
      parameters:
        - name: key
          in: path
          type: string
          description: Task key
          required: True
      responses:
        200:
          description: Success
